apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-healthcheck
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo-apps
        image: gdabli90/k8s-demo-apps
        ports:
        - name: nodejs-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30