apiVersion: v1
kind: Pod
metadata:
  name: helloworld-k8s-demo
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo-apps
    image: gdabli90/k8s-demo-apps
    ports:
    - name: nodejs-port
      containerPort: 5000
